version: "3"
services:
    api:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        working_dir: /code
        environment: 
            MAX_NUMBER_SUPPORT: 99999
            MIN_NUMBER_SUPPORT: -99999